name: Feature Request
description: Suggest a new feature or enhancement for HyFixes
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature! Please fill out the form below.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of what you'd like to see added.
      placeholder: "I would like HyFixes to..."
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem this solves
      description: What problem or pain point does this feature address?
      placeholder: "Currently, when X happens, players experience Y..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: "I've tried X but it doesn't work because..."
    validations:
      required: false

  - type: dropdown
    id: plugin-type
    attributes:
      label: Which plugin would this affect?
      options:
        - Runtime Plugin (hyfixes.jar)
        - Early Plugin (hyfixes-early.jar)
        - Both
        - Not sure
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other context, screenshots, or information about the feature request.
    validations:
      required: false
